# Site settings
title: Ondrej Ruttkay
email: oruttkay@gmail.com
url: https://0nko.github.io
description: "Freelance Software Developer. Creator of Salmon Mobile Navigation."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 29B6F6 #80B3FF
  secondary: 0277BD #FD6E8A
  secondary-dark: 01579B #A2122F

# Footer settings
footer:
  copyright: Ondrej Ruttkay
  location: Mailing Address
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/0nko
  - title: facebook
    url: http://facebook.com/ondrejko
  - title: google-plus
    url: http://plus.google.com/+OndrejRuttkay
  - title: linkedin
    url: http://linkedin.com/in/ondrejruttkay
  - title: github
    url: http://github.com/0nko

# Postal address (add as many lines as necessary)
address:
  - line: Varsavska 715/36
  - line: 120 00, Praha 2
  - line: Czech Republic

# Credits content
credits: 'Built using Freelancer, free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
